- name: copy the app to the target
  copy:
    src: "{{ build_root }}webserver-{{ version }}.jar"
    dest: "{{ app_root }}/server.jar"
    remote_src: no
  become: yes
  tags: app
- name: copy the app start file to the target
  copy:
    src: "start.sh"
    dest: "{{ app_root }}"
    remote_src: no
  become: yes
  tags: app
- name: register the server as linux service
  template:
    src: "webserver.service"
    dest: "/etc/systemd/system/"
    remote_src: no
  become: yes
  tags: app
- name: Restart service in all cases
  service:
    name: webserver
    state: restarted
- name: register the server as linux service
  template:
    src: "webserver2.service"
    dest: "/etc/systemd/system/"
    remote_src: no
  become: yes
  tags: app
- name: Restart service in all cases
  service:
    name: webserver2
    state: restarted