- name: Add the influx user '{{ systemgroup }}'
  user:
    name: "{{ influxuser }}"
    comment: influx user
    shell: /bin/bash
    groups: "{{ systemgroup }}"
    append: yes
  become: yes
- name: create influx data directory
  file:
    path: "{{ data_root }}"
    state: directory
    owner: "{{ influxuser }}"
    group: "{{ systemgroup }}"
    mode: 0775
  tags: structure
  become: yes
- name: create influx config directory
  file:
    path: "{{ config_root }}"
    state: directory
    owner: "{{ influxuser }}"
    group: "{{ systemgroup }}"
    mode: 0775
  tags: structure
  become: yes
- name: copy config to config folder '{{ config_root }}'
  template:
    src: config.yml
    dest: "{{ config_root }}/config.yml"
    owner: "{{ influxuser }}"
  become: yes
  tags: config
- name: copy influx.docker start to docker root
  template:
    src: "influx.docker"
    dest: "{{ dockerroot }}/influx.docker"
    owner: www-data
    group: "{{ systemgroup }}"
    mode: 0750
  become: yes
- name: copy env file as a base template to docker root
  template:
    src: env-file
    dest: "{{ dockerroot }}/.influx.env"
    owner: www-data
    group: "{{ systemgroup }}"
    mode: 0750
  become: yes
- block:
    - name: remove the old container
      shell:
        cmd: 'docker stop influx && docker rm influx'
      become: yes
      tags: programs
  rescue:
    - name: nothing to remove
      shell: "echo 'nothing to remove'"
      become: yes
      tags: programs
- block:
    - name: start the container
      shell:
        cmd: '{{ dockerroot }}/influx.docker'
      become: yes
      tags: programs
  rescue:
    - name: restart the container
      shell: "docker restart influx"
      become: yes
      tags: programs